#lang pollen
◊(define-meta doc-publish-date "2025-06-14")

◊(title "FPTP and wasted votes"
    "Electoral theory and the philosophy of voting")
◊(print-date)

◊block-note{
This essay is a follow-up to a ◊a[#:href "why_fptp_is_great.html"]{previous work} in which I
defend ◊i{first-past-the-post} as an electoral system.
}

◊initial-cap{One of the} most common criticisms of ◊i{first-past-the-post} (◊acro{FPTP}) in legislative elections is that it is unrepresentative because of ◊i{wasted votes}. In the United States, for example, voters in deeply conservative or progressive districts often feel that their votes don't really matter, since the district's result was never in question. If a district is already solidly Republican, it can feel like every further Republican vote above fifty percent is pointless. Conversely, a Democratic voter in such a conservative district might not even show up to vote, since there's virtually no chance that his vote will swing the final result. The critics cast this not as some quirk of American politics, but a fundamental flaw of ◊acro{FPTP} elections that makes ◊i{proportional representation} (◊acro{PR}) superior.

◊sidenote{The term ◊em{wasted votes} can refer to both ◊i{disproportionality} (which calls for ◊acro{PR}) and ◊i{vote-splitting} (which calls for ◊i{ranked-choice voting}). This essay focuses on the former.}

Yet in a sense, all electoral systems have wasted votes. Every voting system forces each political party to clear a series of thresholds to secure an additional seat in the legislature. Even a purely proportional system with no explicit threshold still implicitly does this due to the finite number of seats available. Regardless of system, this means that any vote could be thought of as wasted if it didn't directly push a party over the threshold to win another seat. Thus the key difference between ◊acro{FPTP} and ◊acro{PR} is not that the former wastes votes, but rather that it makes votes ◊i{non-fungible} (i.e. non-transferrable) across districts. 


To really make this clear, imagine a hypothetical system of ◊acro{FPTP} where voters could cast their ballot at any district of their choosing, without being limited to their home district. Assuming that voters from like parties could coordinate their chosen districts, the results would be mathematically identical to ◊acro{PR}: all the voters from small parties would choose the same districts to maximize their chance of getting a plurality in each. If a party can get enough votes to clear this threshold, it wins a seat in the legislature. If not, those votes are wasted. This example may seem silly, but the main point is that ◊acro{FPTP's} main contribution is the ◊i{constraint of spatial non-fungibility}, not thresholds.

Thus the ◊i{wasted vote} argument for ◊acro{FPTP's} inferiority is really a complaint that it doesn't allow the transfer of votes across districts to meet each successive threshold. The argument implicitly compares ◊acro{FPTP} with an ideal where such a constraint doesn't exist—that is, it assumes a system of proportional representation. You can see the flaw in the logic: ◊i{◊acro{FPTP} is inferior to ◊acro{PR} because…it's not proportional}. It assumes all voters should be interchangeable across regions and then treats any deviation from that as waste. But that begs the question.

So that's it then, right? It's just a popular bit of specious reasoning. But there's also a deeper, more interesting shade to the debate over wasted votes, one that touches on the philosophy of democracy itself. First, one could argue that virtually every vote in a given election is wasted, because the chance that it actually changes the outcome is vanishingly small. This is known as the ◊i{paradox of voting}, and it can make voting itself seem logically irrational—or at least a beautiful leap of faith.

Second, what does it mean for an election to represent the people fairly? Despite the paradox of voting, people have an intuitive sense that some elections are more fairly designed than others. It would be thin gruel for a white Southerner to tell a black American that his votes wouldn't matter anyways, even if he could cast a ballot. And malapportioned systems where certain regions have more representatives can rub people the wrong way. On this more subjective level, the critique of ◊acro{FPTP} seems fair: why should it be that a citizen's vote is more or less likely to change the outcome depending on where he lives? Doesn't this undermine the idea of ◊i{one man, one vote}?

Set aside the fact that most real-world examples of ◊acro{PR} wade into this via explicit thresholds and district magnitudes. The deeper question is whether the constraint of spatial non-fungibility is fundamentally unfair, even when the districts are drawn in earnest and apportioned evenly. It also further raises the question about its effects on smaller parties: is it really fair to them that the rules try to smother them?

We must first keep in mind that democracy above all seeks to represent human beings, channeling their hopes and fears into political power that can protect the general welfare. Political parties themselves do not live and breathe; it is their members whose concerns a democracy should heed, not the formal structures themselves. It may be prudent to let voters easily form their own political parties, but it is no less democratic to corral them into bigger-tent organizations, so long as the freedom and consequence of dissent remains.

Indeed, one could argue that ◊acro{PR} weakens accountability by stripping out the spatial information transmitted by elections. ◊acro{FPTP} is essentially a form of ◊i{mode-based downsampling}: it creates a compressed map of a country's factional diversity by dividing it into small pieces and filling in each according to the most-picked candidate. Broad-based factions centred around ideology are pushed towards big-tent coalitions, while regional movements are given the space to compete without having their support averaged out of existence, smeared across the entire electoral map.

This geographic information matters. Aggrieved regional factions can become hotbeds for rebellion or secession—it makes sense to give them representation on their own terms, instead of stuffing them into a big-tent party. More generally, ◊acro{FPTP's} spatial data makes it a metal detector for tribalism, giving them special representation instead of ignoring their concerns. The reason is that  tribalism tends to result in ◊i{self-sorting}: if people's fealty to a faction becomes tribal, they tend to cluster together into enclaves that are picked up by ◊acro{FPTP}. A society riven with tribal tensions can thus give each group a seat at the table, while less tribal, more ideological factions are guided into powerful blocs that can act decisively where possible.

Tribalism—where dignity inheres not in human beings but in one's kin or clan—is the greatest threat to a plural society. It is not a simple empirical disagreement that can be resolved through testing new policies, but a kind of mutual distrust where their gain is your loss, and their triumph your life.  ◊acro{FPTP} recognizes this: where a society is unified, it allows for settling empirical disagreements by letting strong majorities test their ideas in full; but when a society is fractured into tribes, it pushes for compromise. One man still has one vote, but his choice is filtered through these demographic realities.

◊acro{FPTP} therefore doesn't cause polarization or tribalism, but reveals it—a bitter pill for many Americans who have watched as electoral lines have hardened into almost sectarian divisions. Though the two-party system remains, such voting patterns have led to districts whose voters choose the same party regardless of blunders or missteps: a classic sign of political tribalism. Yet saying that votes in such districts are wasted takes for granted the millions of thoughtful people who reaffirm their choices every election, and ducks the harder truth about the underlying cause.

All the other critiques—gerrymandering, the Electoral College, wasted votes—similarly miss the point. None of these would matter if the ◊acro{USA's} federal polity were less regionally polarized: gerrymanders would become unstable, the Electoral College would expand beyond just a few ◊i{swing states}, and districts would shift between parties as new issues arose and resolved. It is rather a nationalized culture war and a paralyzed federal structure that allow partisan identities to harden into tribal ones. So long as the stakes remain so high, the electoral map will remain frozen. In this sense, the wasted votes are the most important ones of all—a warning sign.
◊(end-mark)
